### ISSUE TITLE
November 2017 monthly community call

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#10]
### Next date:
23rd November at 10:30 AM GMT. 

### Agenda:

- getting back up and running after our hosting expired. See also #5 #8 for migration plans and #9 for a short-term stopgap that @xwatkins is helping out with. 
- Should we apply for OBF membership to help maintain our longer-term stability? See the [OBF membership application docs](https://github.com/OBF/obf-docs/blob/unratified-drafts/Affiliated-Project-Policy.md)
- GSoC projects. Do you have ideas or want to be a mentor? Discuss or add project ideas here: https://github.com/biojs/organisation/issues/7 

### Call-in details

Zoom conference ID is here:
https://unimelb.zoom.us/j/6552003787

BioJS Monthly Community Call (10.30am GMT on the fourth Thursday of every month)

Using emails from the BioJS Internal Google Group. Please email rowland@stemformatics.org if you cannot remove yourself from the list.

https://groups.google.com/forum/#!forum/biojavascript

Or join Zoom by phone:
Dial: +61 2 8015 2088
Meeting ID: 655 200 3787
International numbers available: https://unimelb.zoom.us/zoomconference?m=MB2Ciocm74cBW8nyXg3XVbGY5vqzsDnd

Or join Zoom from a H.323/SIP room system:

Dial: SIP:7588@aarnet.edu.au
or H323:6552003787@182.255.112.21 (From Cisco)
or H323:182.255.112.21##6552003787 (From LifeSize or Polycom) 
or 162.255.36.11 or 162.255.37.11 (U.S.)
Meeting ID: 6552003787

**Comment by rowlandm** [comment]
Thanks Yo - I didn't realise it was this week!

**Comment by yochannah** [comment]
hah - between us we'll keep this thing stumbling along 😆

**Comment by rowlandm** [comment]
Key action points from the meeting:

1. DNS is not working for biojs.net and workmen.biojs.net. Need to re-delegate DNS from GoDaddy (Rafa) to Cloudflare [ @DennisSchwartz ]

2. #11 Passwords storage online. Also change Twitter password  [ @yochannah ]

3. #12 Create two NeCTAR VMs for Dennis and Yo. Give them both access. Ubuntu with not much grunt needed. [ Rowland]

4. Ask a little more about what being a part of OBF will mean for BioJS [ @yochannah ]

5. Write up projects as Issues for Google Summer of Code [Everyone]

6. #13 Write up a rough system architecture guideline as an issue [Rowland]

Other topics:
1. Leyla discussed something about web components (sorry I couldn't hear too well!)
2. Dinesh joined us and wanted to help with actual components (thanks for joining us!)

**Comment by xwatkins** [comment]
completely missed it, will try to join the next one

**Comment by yochannah** [comment]
The second part of item 2. above has been completed - Rowland, I've sent you details

**Comment by yochannah** [comment]
I think these are all resolved.
