### ISSUE TITLE
Sort out passwords - lastpass?

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#11]
This is a possible web-based solution to share all biojs passwords safely -
 core active members could have access to the master password. 

https://www.lastpass.com/

**Comment by yochannah** [comment]
@rowlandm what do you think?

**Comment by rowlandm** [comment]
I think it should be OK. I saw this article that mentions that you shouldn't let it store your master password. If we do that I think we should be fine.

At the very least, if you use LastPass, don't allow it to store your master password and, as Vigo and Garcia recommended, enable the service's two-factor authentication option. If you don't use LastPass, perhaps the smartest option, as three Microsoft researchers suggested last year, is to reuse passwords for low-priority accounts and then memorize a few difficult ones for accounts whose compromise would be very undesirable, such as Webmail, social-networking and online-banking accounts.

https://www.tomsguide.com/us/lastpass-security-flaws,news-21826.html

**Comment by DennisSchwartz** [comment]
I like it. I'll have to take a closer look to see if there is cost involved.

**Comment by rowlandm** [comment]
I think it's free for 1 user. We would then just share the one master password between three people.'

Other options is KeepassX

**Comment by yochannah** [comment]
I've set up a free account, but since we blocked the password doc I can't
migrate details there :( Happy to do it if someone share the details with me

**Comment by DennisSchwartz** [comment]
I granted you access on GDrive. Give it another go and let me know if it works.

**Comment by yochannah** [comment]
All good! :)

**Comment by yochannah** [comment]
Passwords have all been migrated to lastpass. DO NOT USE THE GOOGLE DOCS!

Lastpass credentials are held by @yochannah, @DennisSchwartz and @rowlandm
