### ISSUE TITLE
Setup 2x NeCTAR VMs for Yo and Dennis

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#12]
Ubuntu
Using AWS microservice at the moment.
Need @DennisSchwartz and @yochannah public keys

**Comment by DennisSchwartz** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSniDM5zfnd0DAuUyQ17lkesTOYg/y05jS7O85HrVI/tkiZIBbmqMf9VgDL302PCBkiY1p4NPjdxygQa+gnsVWpEnpgzI2hSOeQu0afMOTWZu7OQ/o72wJb/R+8Fr+eLcpxOPADu6jbqV6mIkStM5DAeez8rnu8NzIQiM6z0fFeIhpU8VFBL1Xlq/ZEiLt9Z45Rahi4qPxEGEW3OB83LgxB9ea1UF+Xii/S9SNOxE/
eFUyspp1pmt1Q1cxGC7p5W72FMH8eqM+1mUx/eEso+yxB+xyh2wPoqs3Bun4Py9HdP8WLzlSGpPN9MCDL0tF+xuEiXQifdaeZl5d+Ae3PRUH5icOrUhb1mYdgdnyba2ljyum10XWO5wPg3vAKSnlbZLzCMpI4EXn7cc+lVIK15Ga/8xbDEjl7IiC/l+uGvsM99t8lh/XMD8pv7HPiZ5QB+A2fX34B/vIpSg1b5cHNfNs1vl/sVWieIMUcMGHsy10ZBwnbePTDcJw7miS
z9sO8+JbqQTmwzKqEBiOEdd6cPYf0UiChAzguUJgxdZAo0K0C8AVrv6r46Swxb0CIFImqU/DZF0F1z/Cv50pZA4DTvBDnW/vwaxZ5Xtw3xydoCfpemBHZelHaxZS7qt6rhzERb5yV3SPLiKyVtVdGSEf/74dnDj0FGxnxSYiUNpbJ+6F9Q== dennis@repositive.io
```

Thanks @rowlandm!

**Comment by rowlandm** [comment]
Hi Dennis,
I have setup biojs1.stemformatics.org (Sydney) and biojs2.stemformatics.org (Melbourne).
You should be able to ssh in:
ssh dennis@biojs1.stemformatics.org

Let me know if that's not the case.

I will need to give you your password (please change it) for your sudo access. 

Rowland.

**Comment by rowlandm** [comment]
Yo is setup as well, but without her public key.

**Comment by rowlandm** [comment]
Be warned, there is no iptables on these servers. They are very bare boned.

**Comment by yochannah** [comment]
Thanks Rowland!!

**Comment by DennisSchwartz** [comment]
Thanks a lot! I will check them out tomorrow or tonight.

**Comment by yochannah** [comment]
having trouble sshing with username / password. I'm guessing the user is yo?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq/v2f2BdG9md4rpz/5wsuKtd8DdfUlHPGqCyCCmMd3vLDNdKP4MR7Tr5HyGckIfyQvNY4+ioClylo0AUARzWHrIdN2yS82UNV181KsMX0kZWtolOn/TPGM8+1Ok0qafOvbY+U4JD2wgMbj3adQPKzeWFCHRe6+cp1fJWpx1NPcKbHI6drQ+szIKnTQ3Y8j6ar1/xGV7PbSBwy2e0I6uxXQKashjpjQNS3QHodDhJMkXLKS3xI3WLkzWHG0efuog7p86O4RsmNli+lA/5ZFrEiaMeCRheEP9DKlezp/FobMVjFW3RzJVV9nuZ1/MUNbhy05adQHCutbDj6miF3p2yPb5iGDb+q2+Fgbslml6mlZLQ7z9fL7K+Kn95HEPntGWQvFVRWhVvFthbnW6D2q+WABxJj4s+ZzEG9kKoQ7L/tGXb6HLA/RKynx1FYveUA8DqPgUVbJXMvoc3Y/9ZK0ud7MbS5VZ5C2rDdVZ5H1NEC1wI1atZTpJqyYJxBPQs+8Oit/zV07e4RjM69oEbvuhApeFEogWox+SnsVQBUKnmo9ou8EEzMSbmtjmpSAakuOvX0TCOQuec+Yp1I2aKyukpzHZfC9NRrSomAQBIBTctD19UCWFvD4UUA56JZZXo8PinxE+jM76IVKRGqBxa9iFy5jPGgD0mWkGRFPrTGQ+9DQw== yochannah@gmail.com
```

**Comment by rowlandm** [comment]
Can I get your public key?

I'll check with username/password. Yes it is yo

And it's locked down by public key only.

**Comment by yochannah** [comment]
Key is:

 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq/v2f2BdG9md4rpz/5wsuKtd8DdfUlHPGqCyCCmMd3vLDNdKP4MR7Tr5HyGckIfyQvNY4+ioClylo0AUARzWHrIdN2yS82UNV181KsMX0kZWtolOn/TPGM8+1Ok0qafOvbY+U4JD2wgMbj3adQPKzeWFCHRe6+cp1fJWpx1NPcKbHI6drQ+szIKnTQ3Y8j6ar1/xGV7PbSBwy2e0I6uxXQKashjpjQNS3QHodDhJMkXLKS3xI3WLkzWHG0efuog7p86O4RsmNli+lA/5ZFrEiaMeCRheEP9DKlezp/FobMVjFW3RzJVV9nuZ1/MUNbhy05adQHCutbDj6miF3p2yPb5iGDb+q2+Fgbslml6mlZLQ7z9fL7K+Kn95HEPntGWQvFVRWhVvFthbnW6D2q+WABxJj4s+ZzEG9kKoQ7L/tGXb6HLA/RKynx1FYveUA8DqPgUVbJXMvoc3Y/9ZK0ud7MbS5VZ5C2rDdVZ5H1NEC1wI1atZTpJqyYJxBPQs+8Oit/zV07e4RjM69oEbvuhApeFEogWox+SnsVQBUKnmo9ou8EEzMSbmtjmpSAakuOvX0TCOQuec+Yp1I2aKyukpzHZfC9NRrSomAQBIBTctD19UCWFvD4UUA56JZZXo8PinxE+jM76IVKRGqBxa9iFy5jPGgD0mWkGRFPrTGQ+9DQw== yochannah@gmail.com

**Comment by rowlandm** [comment]
try 
ssh yo@biojs1.stemformatics.org

**Comment by yochannah** [comment]
yep, that's fixed it. Thanks! :+1:

**Comment by rowlandm** [comment]
OK - will do it for biojs2 now.

**Comment by rowlandm** [comment]
Try now for biojs2.stemformatics.org

**Comment by yochannah** [comment]
looking good!

**Comment by rowlandm** [comment]
Check your sudo access too. Just want to ensure it's all OK.

**Comment by yochannah** [comment]
all good! passwords changes and cowsay installed as a test package on both.

**Comment by DennisSchwartz** [comment]
@rowlandm I get an `Permission denied (publickey).` error 🤔 

Can you check if there maybe is an issue with newlines or something?

**Comment by rowlandm** [comment]
Try now!

Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.

**Comment by DennisSchwartz** [comment]
@rowlandm It works for `biojs1`! 🎉  That's enough for now, but if you have time to do it for the other machine as well, that would be great.

Thanks again! I'll have time to work on it tonight.

**Comment by rowlandm** [comment]
Ok - done on biojs2. Please let me know if you can't get in.

**Comment by rowlandm** [comment]
Hi @DennisSchwartz  and @yochannah 

Once you can get into these two VMs and check sudo, you can close this issue.

**Comment by DennisSchwartz** [comment]
Works for me! Ready to close from my side.

Thanks @rowlandm!

**Comment by yochannah** [comment]
All good!
