### ISSUE TITLE
 2018 road map

### ISSUE THREAD

**Issue by alexgarciac** [biojs/organisation#14]
we need to have fortnightly calls/sprints to define a 2018 road map for biojs. interested?

**Comment by ljgarcia** [comment]
Currently, we have a monthly call, the last Thursday as farvas I 
remember. You could join those.

At this point, not sure we have enough for biweekly meetings, what us on 
iur plate right now is getting the registry properly running and start 
getting a look to the summer of code next year. Perhaps you have some 
ideas for the latter?

Not sure when our meeting this month is, last Thursday can be tricky. 
Should we move it one week ahead?

**Comment by rowlandm** [comment]
I'm going to close this as we haven't had much discussion.
