### ISSUE TITLE
Biojs.io down again

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#17]
Sorry @DennisSchwartz ....

I was checking the patches for the biojs1.stemformatics.org server and realised that it was out of space.

I initially thought it was an open file so I just rebooted the server. The web service didn't come backup after a reboot.

I finally tracked it down to the overlay2 directory that was chewing up 4.4GB of space:
https://forums.docker.com/t/some-way-to-clean-up-identify-contents-of-var-lib-docker-overlay/30604/13

Now I'm trying to rerun the docker containers but nothing comes back when connecting to http://biojs1.stemformatics.org/

We may have to go onto a bigger server....

**Comment by rowlandm** [comment]
I'll create a biojs3.stemformatics.org.

Please note that you can use biojs2.stemformatics.org instead for the moment.

I'm pretty sure I've just screwed docker over on biojs1.stemformatics.org

**Comment by rowlandm** [comment]
I've created biojs3.stemformatics.org with 30GB of space.

You should have the password now too @DennisSchwartz 
We may need to document the exact build instructions so I can clean up my mess a bit better next time.

**Comment by rowlandm** [comment]
@yochannah  - you have access too.

**Comment by DennisSchwartz** [comment]
@rowlandm Ah sorry! I just saw this.

This is a problem with docker. I think the workmen isn't really using a database and instead is just storing stuff on disk.

I restarted it on biojs1 but I'll move it to the 3.

Also, I'm running the docker container manually which isn't the best really. I'll need to look into Kubernetes or Docker Swarm or sth.

**Comment by DennisSchwartz** [comment]
It's up again for now, so closing this issue.

**Comment by DennisSchwartz** [comment]
It's now running on biojs3 as well and the DNS has been updated.
