### ISSUE TITLE
Google Summer of Code Plan of attack

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#18]
Hi All,

Yo and I had a quick talk about the Google Summer of Code.

We discussed a joint Stemformatics and BioJS application, as the OBF doesn't seem to have much energy that we can see in providing us with an umbrella organisation. This is because it may be better to have a few organisations under the one umbrella to get a better chance of being selected.

Other options discussed were:
a) BioJS running as a separate organisation / application
b) other organisations being part of this umbrella application.

Yo and I wanted to make sure that this decision could be discussed by the community. 

It's important to note that if you want to provide input you will have to help write the applications etc!

Deadlines to finalise the decision of how to apply will be the 14th of January and we plan to submit by the 22nd of January (submission deadline is 23rd).

The plan is to have two projects for BioJS, a front end and a back end to replace the three websites, biojs.net, biojs.io and biojs.edu. We would use the mockups for the landing page in #4 as a guide for the project. If you have any input please make comments in #4 

Rowland.

**Comment by rowlandm** [comment]
- Backend project will include DevOps.
- Splash page, LIbrary/metadata search, landing page for each component, visualisation and education.
- Provide expectations in the project plan for how to apply.

**Comment by rowlandm** [comment]
Comment from @manuelcorpas 

We have been successful in the past on our own, in fact this was what led to BioJS 2.0.

**Comment by rowlandm** [comment]
Based on Manny's comments - I'd be happy for BioJS to apply separately.

**Comment by yochannah** [comment]
I'm more inclined towards a shared / umbrella style org (see the note here: https://google.github.io/gsocguides/mentor/org-application ), but if you're willing to do the application then I'll not argue ;) 

I will happily volunteer to be a secondary org admin and / or mentor for one of the two projects, but I don't have time to be a primary mentor, as I'll (hopefully) have a student of my own through InterMine if we get in. 

Yo

**Comment by rowlandm** [comment]
Hi Yo - I didn't see that document before - that's great to clarify.

If that's the case, I would strongly suggest to have an umbrella application. It's pretty much the same work anyway but at least we would have more than one organisation tied to it.

Is there any other organisation who would want to join, even if they were applying as a separate organisation?

**Comment by ljgarcia** [comment]
In order to apply as an umbrella, we need to show multiple organizations/institutions backing it up, do not we? I am not sure we have all that support right now. Yo, do you think Intermine would go for a join application under the BioJS umbrella? What about Stemformatics? Or maybe, should we look to join another group such as Galaxy? I kind of remember this as a possibility from our BoF meeting in July. Anyone from Galaxy on the list that could comment?

**Comment by rowlandm** [comment]
Stemformatics would definitely be part of this. I also want to see if
InnateDB would be part of it, but I haven't asked them yet.

Would UniProt be interested?

Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.

**Comment by ljgarcia** [comment]
What would be required to back up the application? We might get some interest from InterPro as well, @4ndr01d3 what do you think?

**Comment by DennisSchwartz** [comment]
I'm interested in that as well. I'm happy to present this to my boss as well if I know what it entails. He would probably be interested.
We just got a new office, we might be able to spare a desk for a Student ;)

**Comment by rowlandm** [comment]
Probably a willingness to put your oganisations name in the application and
also submit a project for the Project page.

In terms of details for the project, I have written up some for
Stemformatics that you can check out here:
https://docs.google.com/document/d/1zcuCTUMqbR7QFrUaGmxYGD_iKt8XCK6a35RtN6GGUC0/edit#heading=h.6egttnvbi2gu


Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.

**Comment by yochannah** [comment]
@ljgarcia InterMine will be applying as its own organisation this year probably, although in the chance we didn't get in and biojs did we might come humbly begging for some spots ;)

@DennisSchwartz Physical desk spots aren't required for gsoc, although if you *do* end up with someone physically proximate, there's no reason for them not to visit/come to work in person. 

@ everyone - I'd recommend reading through https://google.github.io/gsocguides/mentor/ if you haven't participated in gsoc before. Every student taken on (and every project idea) requires a named mentor and a time commitment from the mentor that could be several hours a week. 

If you're writing a project idea, see the gsoc mentor guide on the requirements for writing a good list: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list

**Comment by yochannah** [comment]
@ljgarcia re galaxy - last year Galaxy used the [Open Genome Informatics](https://summerofcode.withgoogle.com/archive/2017/organizations/4997812655751168/) organisation (same umbrella org that InterMine used.) At this point in time we haven't heard from Open Genome Informatics so I'm not sure what will happen this year! I'll try to find out if they're planning to run again - if not maybe we can invite them.

**Comment by yochannah** [comment]
Update - OBF *will* be applying with any project ideas PRed by the 20th: https://github.com/OBF/GSoC

**Comment by rowlandm** [comment]
OK - I'll be trying to write those two projects up on the weekend.
