### ISSUE TITLE
Revive BioJS edu tutorials

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#20]
[Biojs.edu](http://edu.biojs.net/)

I tried generating a static version to get back up on gh-pages. Didn't go as well as I'd hoped:

- we can't automatically build it in jekyll on gh-pages because it uses a bunch of custom tags and plugins
- it's set up to auto deploy to amazon s3 which isn't a great idea without anyone who wants to pay for it. 
- If you try to generate a static version to manually upload to gh-pages, it works - kinda. 
   - the links are hardwired to be on the root of the hosted domain, which won't for gh-pages which requires a subfolder. I got most of the dead links fixed on a local branch here: https://yochannah.github.io/edu/101/intro/ but ran out of steam trying to edit the ruby files that generate the links for all of the post series: https://github.com/biojs/edu/tree/master/_plugins 
- I'm exhausted now. Shall we just deploy a static copy onto one of Rowland's nectar servers and point the domain root there? There's so much good content there it'd be a shame to lose.

**Comment by DennisSchwartz** [comment]
Hi @yochannah !
I wasn't aware this was down, it wasn't hosted on Heroku so I didn't think it would be affected.

Do you have an idea how much changes we would need to deploy it on gh-pages?
If it's easier to make a static version, I'm totally down for that. It's not really changing much anyway at the moment.

**Comment by yochannah** [comment]
@DennisSchwartz After a quick review of things on Saturday afternoon- there are a lot of custom tags for formatting code, plus the ruby code for generating the links between different lesson series. Possibly other things as well :( 

Using rowland's server is likely to be the fastest option

**Comment by yochannah** [comment]
GSoC applicants - if you'd like to try getting the edu docs to generate statically so we can upload to gh-pages, that would be very welcome!

**Comment by alkesh47** [comment]
@yochannah Is static generation of the edu docs the only reason that's preventing the generation on gh-pages or is there something else too?

**Comment by yochannah** [comment]
@alkesh47 there are plugins that generate links for the tables of contents and generate code highlighting - but github doesn't support most jekyll plugins.

**Comment by alkesh47** [comment]
@yochannah Do we need to stick to gh-pages for hosting? If it doesn't support the plugins then there is a possibility that we could migrate to some other hosting provider?

**Comment by yochannah** [comment]
Ideally it would be nice if we could get it on to gh-pages, because other
hosting generally costs money (that's the reason biojs.edu) is down right
now :( failing that, we could probably put it on the same servers that we
are using for the registry right now.

**Comment by alkesh47** [comment]
No I don't mean some fancy pricy ones, I meant something like gitlab pages, netlify etc. The main concern of mine is that beyond the pricing option, is there anything else that's preventing us from choosing a different (free of cost) hosting provider.

**Comment by yochannah** [comment]
We'll want to resurrect the edu pages - maybe by copy/pasting the content to a new page / repo that isn't so tightly coupled to the hosting like this was.

**Comment by yochannah** [comment]
Looking back at this thank to a prompt from https://github.com/biojs/biojs/issues/166 - we might be able to fix by migrating the edu repo to gitlab. @rgaiacs recently let slip that the gitlab equivalent of gh-pages allows jekyll plugins, so it might be straightforward to set up if we're lucky.

**Comment by yochannah** [comment]
We could also consider throwing this topic into the biohackathon later this year

**Comment by rgaiacs** [comment]
> gitlab equivalent of gh-pages allows jekyll plugins

Guilty. :laughing: Import https://github.com/biojs/edu into GitLab and add https://gitlab.com/pages/jekyll/blob/master/.gitlab-ci.yml to the new repository should make a version on GitLab servers. You can redirect biojs.edu to GitLab servers.

**Comment by yochannah** [comment]
IT IS FIXED!!! 

-> http://edu.biojs.net/ is now backed by gitlab pages - source is here: https://gitlab.com/biojs/edu/

@rowlandm @Megh-Thakkar @sarthak-sehgal (and anyone else appropriate) - I can grant you access to these repos if you message me with your gitlab account users! 

@rgaiacs You are a hero ❤️ ❤️ ❤️ ❤️
