### ISSUE TITLE
BioJS Monthly Community Call for January 2018

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#22]
BioJS Monthly Community Call (10.30am GMT  on the fourth Thursday of every month)

Using emails from the BioJS Internal Google Group. Please email rowland@stemformatics.org if you cannot remove yourself from the list.

Link to meeting room:
https://unimelb.zoom.us/j/6552003787

https://groups.google.com/forum/#!forum/biojavascript

Or join Zoom by phone: 
    Dial: +61 2 8015 2088
    Meeting ID: 655 200 3787 
    International numbers available: https://unimelb.zoom.us/zoomconference?m=MB2Ciocm74cBW8nyXg3XVbGY5vqzsDnd

Or join Zoom from a H.323/SIP room system: 

    Dial: SIP:7588@aarnet.edu.au
    or H323:6552003787@182.255.112.21 (From Cisco)
    or H323:182.255.112.21##6552003787 (From LifeSize or Polycom) 
    or 162.255.36.11 or 162.255.37.11 (U.S.)
    Meeting ID: 6552003787

**Comment by rowlandm** [comment]
Calendar here:
https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=1&day=25&hour=10&min=30&sec=0&p1=136&p2=152&iv=1800

**Comment by yochannah** [comment]
I'm not going to be able to make this unfortunately - I seem to have picked up the flue when I was in France :(

**Comment by rowlandm** [comment]
No worries.

**Comment by rowlandm** [comment]
Hi everyone,

I don't have much of an agenda. Just mainly an update on:
- Google Summer of Code
- Fixing problems with the BioJS workmen servers
- Closing old things no longer used that someone is still paying for

**Comment by rowlandm** [comment]
Just to remind everyone the Zoom meeting link is here:
https://unimelb.zoom.us/j/6552003787

**Comment by rowlandm** [comment]
- AWS has been shutdown
- GSuite we are trying to shutdown, we have emailed Manny about this
- We should check Heroku to see if there is an account outstanding
