### ISSUE TITLE
Unstable workmen

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#24]
Hi all,

This is the second or third time this has fallen over in the last 3 months. That is very unstable. I can't tell if it's 

I think we need to be very aware of reliability and maintainability when we make our software architecture choices. We don't have a lot of contributors so I think we need to prioritise this over anything else, even contributor preferences.

What are your thoughts @DennisSchwartz  and @yochannah ?

---------- Forwarded message ----------
From: Uptime Robot <alert@uptimerobot.com>
Date: Tue, Feb 13, 2018 at 12:24 AM
Subject: Monitor is DOWN: BioJS Workmen
To: info@stemformatics.org

Hi,

The monitor BioJS Workmen (http://workmen.biojs.net/) is currently DOWN (Keyword Does Not Exist). 

Uptime Robot will alert you when it is back up.

Sincerely,

Uptime Robot
http://uptimerobot.com
http://twitter.com/uptimerobot
http://facebook.com/uptimerobot

P.S. Get notified of downtime faster (1-minute checks) with the Pro Plan for only $4.5/month (for details: http://uptimerobot.com/pricing).

**Comment by yochannah** [comment]
Is our feeling that it's to do with the workmen server itself or the infrastructure? I'm not close enough to the technical side to make a verdict. If we think it *is* infrastructure, we might be able to apply for help: http://osuosl.org/services/hosting/

**Comment by rowlandm** [comment]
It's definitely the docker/workmen server. The VM is still running and
seems fine.

**Comment by rowlandm** [comment]
I fixed it for now with:

`  102  docker rm workmen
  103  docker run --name=workmen -e GITHUB_TOKEN=4f5c492f909d1013576a411a39915348a4743b15 -e NODE_ENV=production -p 80:5000 -p 443:5000 --network=workmen -d biojs/workman`

**Comment by rowlandm** [comment]
docker ps - brought up nothing
docker workmen was still there so I had to remove it
docker rm workmen

docker run --name=workmen -e GITHUB_TOKEN=<insert_token_here> -e NODE_ENV=production -p 80:5000 -p 443:5000 --network=workmen -d biojs/workman

**Comment by DennisSchwartz** [comment]
This is the error causing it to crash:

```
info: Listening on port 5000
/opt/node_modules/nedb/lib/datastore.js:61
    if (err) { throw err; }
               ^

RangeError: File size is greater than possible Buffer: 0x7fffffff bytes
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:330:11)

npm info biojs-registry-workmen@0.2.0 Failed to exec start script
npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! biojs-registry-workmen@0.2.0 start: `node server.js 5000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the biojs-registry-workmen@0.2.0 start script 'node server.js 5000'.
npm ERR! This is most likely a problem with the biojs-registry-workmen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js 5000
npm ERR! You can get their info via:
npm ERR!     npm owner ls biojs-registry-workmen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/npm-debug.log
```

It's a database issue. Not sure if it's worth looking into anymore.

**Comment by rowlandm** [comment]
Leave it for now. Sounds a bit dodgy given how tiny the data is.
