### ISSUE TITLE
Text overflow at various places in biojs.io

### ISSUE THREAD

**Issue by sarthak-sehgal** [biojs/organisation#26]
## Issue
The text is exceeding the circle boundary as you can see here:
![biojs issue 1](https://user-images.githubusercontent.com/29003134/36362708-24483eb2-155d-11e8-9dab-90664cb4431f.png)

## Suggested fix
A circle will either grow bigger to adjust the text or we will have to decrease the text size. Neither of the solutions seems to be a good fix. 
I suggest that the UI should be something like this:
![biojs issue solve 1](https://user-images.githubusercontent.com/29003134/36362732-6916223e-155d-11e8-9dfc-772b4f4ee591.png)

And, in fact, the background should be in contrast with the white colored text. So I suggest to make the background a bit darker and the text bolder as in:
![biojs issue solve 2](https://user-images.githubusercontent.com/29003134/36362775-b971bf5e-155d-11e8-92f0-ddcab16f5b1e.png)

**Comment by sarthak-sehgal** [comment]
@yochannah @rowlandm 
Would like to work on this if this is an appropriate issue.

**Comment by rowlandm** [comment]
I like the darker background colour.

That's fine to work on Sarthak.

**Comment by fireballpoint1** [comment]
How about doing a round off like 18k for the first case and we can put the real value on hover?
@rowlandm 
We can retain the disc background in that case

**Comment by sarthak-sehgal** [comment]
@fireballpoint1, I think putting numbers (or something else dynamic) in a circle is never a good idea. If you round it off, it will create an issue when it further increases (e.g.: 100k).
Also, I suggested the change in the background color to increase the contrast with the text color so anyhow we will have to change it. :)

**Comment by abhinavvisen** [comment]
@sarthak-sehgal @rowlandm how about instead of notifying the number of downloads ,can we go with the dynamic popups.

**Comment by rowlandm** [comment]
Welcome @abhinavvisen 

Sorry - I'm not quite sure what you mean there?

Did you mean hover over?

**Comment by abhinavvisen** [comment]
@rowlandm Yes i was thinking of that.
By the way sorry for late response.:)
I am working on a mockup right now.It will be clear when i am done with it.
