### ISSUE TITLE
Tips for GSoC 2018 students

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#27]
Hi there,

I have put together a few things around what we are looking for in our GSoC 2018 students:

https://docs.google.com/presentation/d/1LbkgW07l5yKYneAzQFhYQOHup6JCPXlLJ9bJPtBI4Qg/edit#slide=id.p

Please have a look and if you have any comments, you can add them into the document or add them here.

**Comment by yochannah** [comment]
Hey Rowland - looks good!
