### ISSUE TITLE
BioJS Monthly Community Call  for March 2018

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#28]
https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=3&day=22&hour=10&min=30&sec=0&p1=152&p2=136

BioJS Monthly Community Call (10.30am GMT on the fourth Thursday of every month)

Link to meeting room:
https://unimelb.zoom.us/j/6552003787

Link to chatroom
https://gitter.im/biojs/biojs

Or join Zoom by phone:
Dial: +61 2 8015 2088
Meeting ID: 655 200 3787
International numbers available: https://unimelb.zoom.us/zoomconference?m=MB2Ciocm74cBW8nyXg3XVbGY5vqzsDnd

Or join Zoom from a H.323/SIP room system:

Dial: SIP:7588@aarnet.edu.au
or H323:6552003787@182.255.112.21 (From Cisco)
or H323:182.255.112.21##6552003787 (From LifeSize or Polycom)
or 162.255.36.11 or 162.255.37.11 (U.S.)
Meeting ID: 6552003787

**Comment by rowlandm** [comment]
Please write down any agenda items:
1. Infrastructure update - Rowland
2. Google Summer of Code update - Rowland

**Comment by rowlandm** [comment]
From last months call:
https://github.com/biojs/organisation/issues/25

**Comment by rowlandm** [comment]
3. Joining the OBF? Yes, we should.

**Comment by rowlandm** [comment]
4. Get Yo into biojs3.stemformatics.org.

**Comment by rowlandm** [comment]
Agenda 1. Resetup biojs1 and biojs2 with larger space - ensure Yo and Dennis are available.

**Comment by rowlandm** [comment]
2. GSoC - private mentors talk. Talked about OBF slots.

**Comment by rowlandm** [comment]
Actions Items:
1. Rowland: Get Yo into biojs3.stemformatics.org
2. Yo: Petition to get BioJS into the OBF
3. Rowland: Resetup biojs1 and biojs2 with larger space - ensure Yo and Dennis are available.
4. Everyone: organise to catchup online after the GSoC project proposal deadline closes.


Other comments:
1. Need to ensure that if Rowland was to leave, that Isha from Stemformatics could help support the community as a sysadmin and that Nectar servers stayed with biojs. Also ensure a proper handover.

**Comment by ljgarcia** [comment]
Hi all,

Sorry to miss the call today but it clashed with another activity. I'm 
glad to see how well you're doing, great job!

Cheers!
