### ISSUE TITLE
Options availaible on secondary biojs-registry page do not work

### ISSUE THREAD

**Issue by abhinavvisen** [biojs/organisation#29]
![image](https://user-images.githubusercontent.com/14180717/37804969-3b62ab5a-2e5d-11e8-9560-6f64b337efa0.png)
The options (New Window,Edit(JSBin),Edit (Codepen),Edit(Plunker),All) do not respond and always go to a blank page.

**Comment by yochannah** [comment]
We'll be replacing the registry in the next few months with a rebuilt version so closing this ticket
