### ISSUE TITLE
Update of the BioJS library

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#3]
I've had a quick look into what is currently running the BioJS library. Here's the low down:

The library is run by a 
- Express.js server
- Node 0.12 (!)
- Deployed to Heroku by Travis CI

The code style is more object-oriented and based around objects and prototypes. I personally suggest to move to a more functional approach to allow better testing, but that's up for debate. 
The server actually has quite a bit of functionality and if we want to keep all of it, it will mean a lot of work before we can move over. Maybe we can deal with a bit of a functionality cut for a while.

It 
- Collects all packages in npm through api.npmjs.org
- Displays stats for each package
- Creates a demo instance of the component if provided
- Creates a JSBin for the example
- Allows download as zip file
- Allows search for components
- Supports tags/keywords as filters

These are the endpoints:
```javascript
app.get('/all', queries.all);
app.get('/stat', queries.stat);
app.get('/logs', queries.logs);
app.get('/search', queries.search);
app.get('/detail/:name', queries.detail);

// interactive
app.get('/demo/:name/:snip', snip.demo);
app.get('/demo/:name/:snip/*', snip.demo);
app.get('/demo/:name', snip.overview);

// forwarder
app.get('/codepen/:name/:snip', snip.codepen);
app.get('/jsbin/:name/:snip', snip.jsbin);
app.get('/plunker/:name/:snip', snip.plunker);

// proxies
app.get('/github/:name/:repo/*', snip.github);

// news
app.get('/news/rss', notify.rss);
app.get('/news/atom', notify.atom);
app.get('/news/json', notify.json);
```

Since we're BioJS, I personally would prefer to stick with a Node.js app. My suggestions would be:

- Use Node 8.x (LTS)
- Use latest MongoDB
- Keep Express or move to HapiJS
- Stream data from mongo to have immediate display of components
- Potentially add pagination on top of it.
- Provide search.

Please add anything I've missed here. I'm hoping we can get this going one step at a time :)

**Comment by rowlandm** [comment]
Thanks for this Dennis.

I think this touches on a couple of things:
1/ Our decisions need to take into account the software but also the maintenance of the server and also of the code.
2/ How much functionality is being used at the moment? I'd be loathe to drop anything that was being used consistently...

Dennis, is what you have put together all on the biojs.io website or also on the workmen.biojs.net website? I'm going off the figure below...

![screenshot from 2017-10-03 20-53-45](https://user-images.githubusercontent.com/420050/31119490-fe85e51e-a87c-11e7-9032-9e4a38d97ff8.png)

**Comment by rowlandm** [comment]
Actually I'll add another thing:
3/ It is critical that the code is as simple and maintainable as possible. One rule of thumb is that a junior developer with the architecture diagram should be able to understand the majority of the code within a day or two.

**Comment by rowlandm** [comment]
Also, having a dev/test server as well as a production server would be great. Having them easily able to be setup via a script or DevOps tool would be even better. That way devs who want to contribute could easily spin up a VM and contribute code.

**Comment by DennisSchwartz** [comment]
I'm currently working on this in https://github.com/biojs/workman

**Comment by yochannah** [comment]
I've removed the help wanted label as I don't think a newcomer could come and pick this issue up easily - it's too over-arching.

**Comment by DennisSchwartz** [comment]
Since we now have GSoC Students working on this, I'm going to close this issue for now. Please feel free to re-open if you disagree.
