### ISSUE TITLE
April Community Meeting notes

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#31]
https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=4&day=22&hour=10&min=30&sec=0&p1=152&p2=136

BioJS Monthly Community Call (10.30am GMT on the fourth Thursday of every month)

Link to meeting room:
https://unimelb.zoom.us/j/6552003787

Link to chatroom
https://gitter.im/biojs/biojs

Or join Zoom by phone:
Dial: +61 2 8015 2088
Meeting ID: 655 200 3787
International numbers available: https://unimelb.zoom.us/zoomconference?m=MB2Ciocm74cBW8nyXg3XVbGY5vqzsDnd

Or join Zoom from a H.323/SIP room system:

Dial: SIP:7588@aarnet.edu.au
or H323:6552003787@182.255.112.21 (From Cisco)
or H323:182.255.112.21##6552003787 (From LifeSize or Polycom)
or 162.255.36.11 or 162.255.37.11 (U.S.)
Meeting ID: 6552003787

Agenda:
- Google Summer of Code discussion of what is next
- Get into the OBF
- Get Yo onto biojs3.stemformatics.org (forgot to do!)

**Comment by rowlandm** [comment]
Also: Resetup biojs1 and biojs2 with larger space - ensure Yo and Dennis are available.

**Comment by yochannah** [comment]
Also, galaxy grant...

**Comment by rowlandm** [comment]
Action items:
- Isha to get access to Megh for BioJS server (Sarthak's)
- Share the github repos inside the BioJS Organisation
- Sarthak and Megh to create a blog post with links to github repos

**Comment by DennisSchwartz** [comment]
* Set up development workflow for GSoC
    * Move repos to biojs organisation
    * Formalise process to review and deploy code

**Comment by rowlandm** [comment]
- Ask Kai and Bjoern to see if they want to catchup next time. cc' in Leyla

**Comment by rowlandm** [comment]
- Let Sarthak and Megh decide on what framework/language to use on the backend.

**Comment by bgruening** [comment]
sorry, could not join today :(
