### ISSUE TITLE
Biojs.net is down!

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#35]
Since last night at 8pm BST the biojs.net landing page is down.

```
Hi,

The monitor BioJS Net (http://biojs.net/) is currently DOWN (Keyword Does Not Exist). 

Uptime Robot will alert you when it is back up.


Sincerely,

Uptime Robot
http://uptimerobot.com
http://twitter.com/uptimerobot
http://facebook.com/uptimerobot

P.S. Get notified of downtime faster (1-minute checks) with the Pro Plan for only $4.5/month (for details: http://uptimerobot.com/pricing).
```

I suspect this PR (https://github.com/biojs/biojs.github.io/pull/1) might be the problem. I can't reverse it automatically. 
We might have to check what happened there. 

I'll have some time tonight but probably not before.

**Comment by yochannah** [comment]
Good spot, Dennis.

It looks like the domain name wasn't set up in github pages after the pull.
Fixed now, but the homepage is full of boilerplate. I'll work on that.

**Comment by DennisSchwartz** [comment]
Thanks Yo!

But I seemed to miss the fact that we were planning to replace the landing page with the blog? Maybe we had some miscommunication there. Would be good to talk about that.

**Comment by yochannah** [comment]
Agreed, plus perhaps a clearer PR review process.

I'll make what's there now into a less placeholder look and we can discuss
want we want to take forward later.

**Comment by DennisSchwartz** [comment]
Good call, thanks!

**Comment by yochannah** [comment]
ok, it's by no means perfect but the "test post" is now the same content as the previous homepage. Dennis, I take it you protected the branch so it has to be reviewed before merging? Nice one.

**Comment by DennisSchwartz** [comment]
Yep, but as you can see you can overwrite that if you're an owner ;) I might remove that loophole as well now that it's stable again.

**Comment by DennisSchwartz** [comment]
Thanks a lot Yo!
