### ISSUE TITLE
May monthly community call - move date?

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#37]
**EDIT**: The call is now set at the 31st of May 2018. 

https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=5&day=31&hour=10&min=30&sec=0&p1=152&p2=136

======================================

Hey everyone! The BioJS call would normally be scheduled for the 24th of May as the last Thursday of the month. I'm away this week at my brother's wedding, so was wondering if we could reschedule? Normally I'd be happy to skip the call, but there are a few items on the agenda I'd like to be present for if at all possible. 

Possible options at the same time but different days - please select from the dates in this doodle: https://doodle.com/poll/87tyiebew8yxiimx 

## Agenda

1. Rowland is reducing his hours for BioJS. What transitional arrangements do we need, if any?
    - hosting continuity
    - project management (e.g. call dates). Can someone else step up? 
    - GSoC mentoring. 
2. OBF membership
    - thumbs up from obf so far, but we'll need to go through the process 
    - let's try to add a leadership team page / contacts to the biojs site
    - will need a CoC. 
4. Should we have stronger ties with bionode? 
5. Biohackathon
3. Any GSoC updates?

### Here are the normal call details: 

https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=4&day=22&hour=10&min=30&sec=0&p1=152&p2=136

BioJS Monthly Community Call (10.30am GMT on the fourth Thursday of every month)

Link to meeting room:
https://unimelb.zoom.us/j/6552003787

Link to chatroom
https://gitter.im/biojs/biojs

Or join Zoom by phone:
Dial: +61 2 8015 2088
Meeting ID: 655 200 3787
International numbers available: https://unimelb.zoom.us/zoomconference?m=MB2Ciocm74cBW8nyXg3XVbGY5vqzsDnd

Or join Zoom from a H.323/SIP room system:

Dial: SIP:7588@aarnet.edu.au
or H323:6552003787@182.255.112.21 (From Cisco)
or H323:182.255.112.21##6552003787 (From LifeSize or Polycom)
or 162.255.36.11 or 162.255.37.11 (U.S.)
Meeting ID: 6552003787

**Comment by yochannah** [comment]
Some quick meeting notes:

1. we've blasted through the issues and removed all the aged / complete tickets in this repo.
2. Rowland reducing hours: 
    - Zoom conferencing should be fine for now, Rowland will continue to have access for the forseeable future. 
    - See https://github.com/biojs/organisation/issues/39 for the hosting plan - nectar is probably fine for at least the next six months and probably much longer. 
    - GSoC mentoring will continue as normal until the end of the GSoC period. 
    - Leadership team roles - see #42 
3. GSoC in general - going good, @rowlandm and @DennisSchwartz to ping others (especially me) in issues if further content work is needed. 
4. We should try to schedule a talk with @bionode members to see what community overlaps and cooperation there are. Does anyone know anyone who is active in bionode right now?
5. We need to add a CoC but there aren't many people on the call to agree to it; See https://github.com/biojs/organisation/issues/43

**Comment by DennisSchwartz** [comment]
Bruno from bionode is working part-time for Repositive at the moment. I can talk to him and see if he is still working on it or who is the best person to talk to.

**Comment by yochannah** [comment]
That would be great!
