### ISSUE TITLE
Create list of BioJS papers

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#38]
Where are all the previous BioJS papers? Find them and add to a list on the main website.

**Comment by DennisSchwartz** [comment]
Maybe @manuelcorpas can help?

**Comment by rowlandm** [comment]
Bioinformatics. 2013 Apr 15;29(8):1103-4. doi: 10.1093/bioinformatics/btt100. Epub 2013 Feb 23.
BioJS: an open source JavaScript framework for biological data visualization.
https://www.ncbi.nlm.nih.gov/pubmed/23435069

F1000Res. 2014 Feb 13;3:55. doi: 10.12688/f1000research.3-55.v1. eCollection 2014.
BioJS: an open source standard for biological visualisation - its status in 2014.
https://www.ncbi.nlm.nih.gov/pubmed/25075290

Elife. 2015 Jul 8;4. doi: 10.7554/eLife.07009.
Anatomy of BioJS, an open source community for the life sciences.
https://www.ncbi.nlm.nih.gov/pubmed/26153621

**Comment by rowlandm** [comment]
I think this is all of them.
