### ISSUE TITLE
Review landing page for BioJS

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#4]
I have put together an idea of a redesigned landing page to accomodate just one website domain.

On the Landing page you can click on Browse Component and it will take you to the Browse Component page.

You can click the BioJS logo on the Browse Component Page to get back to the Landing Page.

https://app.moqups.com/rowlandm/qTdAndgOF4/view/page/aa9df7b72

Please have a look and tell me what you think.

**Comment by DennisSchwartz** [comment]
As mentioned before: I like it a lot.

Any ideas what we want to do in terms of a front-end framework?
I've been wanting to learn React for a while :D 
But learning something is usually not the best way to get good results quickly

**Comment by rowlandm** [comment]
I think if you are doing it, you can choose, provided that at least one other person is reviewing the pull requests!

I also think we have to decide if we keep the current infrastructure, start from scratch or something in between.  I think that should be based on ease of development, ease of maintenance and current skillset (and enthusiasm) of whoever is going to do it and maintain it.

**Comment by wilzbach** [comment]
> I've been wanting to learn React for a while :D
> But learning something is usually not the best way to get good results quickly

FWIW React is very easy to ;-)

**Comment by DennisSchwartz** [comment]
Haha, well there's another problem: If I do it by myself it will take forever. We need a better plan than that ;)

I'm happy to take on some, even a lot of it, but I think it's much more important to create a proper document with all the features we want for the first iteration and a vague idea of where they come from.

That'll allow us to really split the work. And from all I've heard, if you want separate components in the front-end, React is the way to go.

We use Ember at work and it's an absolute pain-in-the-ass to get anything to load if some part of the site isn't ready.

**Comment by 4ndr01d3** [comment]
Hey guys,
I'm happy to collaborate as much as my workload allows me. I have some
experience working with React, and agree that it helps in the task of
separating on components. And as Seb said React is quite easy, However,  I
think most of it depends on the project setup, webpack, etc...

Anyways, I agree with Dennis that the priority should be to define the
desired features, how much of this is just merging the 2 domains? how much
of a re-factory?

The other important part is to identify who can actually contribute coding,
this needs to be a community effort and not a solo effort.
Cheers,
Gustavo.

**Comment by DennisSchwartz** [comment]
@4ndr01d3 Totally agree.

And I'm really happy to see so much discussion happening on this already 🤗 
It's not gonna happen overnight, but I'd love to see thing moving ahead in a more collaborative way for BioJS.

**Comment by rowlandm** [comment]
My personal preference is to keep things simple. The actual user interface is pretty simple. I think it's the backend setup that is the one that is more key: https://github.com/biojs/organisation/issues/3

**Comment by ljgarcia** [comment]
I do not expect to have much time to actually code but I would be happy 
to help with code review (that sometime take as much effort as coding, I 
know but not necessarily so might be easier for me to start there, I 
might be able to help more later but we are starting a new project now 
so...)

**Comment by rowlandm** [comment]
Adding your comment from before Leyla:

Looks nice but I would allow the component to take all the horizontal space and just keep a link to Browse Components and a quick Search option.

**Comment by yochannah** [comment]
@rowlandm Your mockup seems to have disappeared (not found when we click on it). Do you have a backup somewhere? 

Maybe you could share it directly in the issue?

**Comment by rowlandm** [comment]
Sorry! I was a bit harsh with my archiving.

It is back up now:
https://app.moqups.com/rowlandm/qTdAndgOF4/view/page/aa9df7b72

Just in case I remove it, I've provided it as a PDF here:
[BioJS_Landing_page_ideas.pdf](https://github.com/biojs/organisation/files/1488686/BioJS_Landing_page_ideas.pdf)

**Comment by alkesh47** [comment]
@rowlandm @yochannah I would like to start working on this issue. I request you to furnish some additional info if necessary that would be important to know before I start working.

**Comment by rowlandm** [comment]
Not much. The only question is how to format the data coming from ajax
calls for the tables.

**Comment by alkesh47** [comment]
@rowlandm Do you have any pointers on how to do that or shall I use the liberty of finding a solution?

**Comment by rowlandm** [comment]
I'd be defaulting to using datatables.js

**Comment by DennisSchwartz** [comment]
@alkesh47 Check out the response from `$ curl workmen.biojs.net/all`. That's what the workman currently returns for the `biojs.io` registry. 

There are more routes (check out `$ curl workmen.biojs.net/` for the readme). The current front-end also uses the `/detail` route a lot which returns more data as far as I can see.

I'm currently re-writing the workman at https://github.com/biojs/workman. So it's quite flexible if you want to see any specific data for the front-end, just let me know.

You basically have the freedom to do whatever you want ;)

**Comment by DennisSchwartz** [comment]
Also, thanks for volunteering your time to work on BioJS 🙃

**Comment by alkesh47** [comment]
@DennisSchwartz Thanks for the useful information. I will begin working on this promptly.

**Comment by alkesh47** [comment]
@DennisSchwartz I'm willing to contribute as much as I can as a GSOC 2018 aspirant 😄

**Comment by alkesh47** [comment]
@DennisSchwartz Shall I create a new repo for tackling this task or is their one you want me to proceed on? Also can you please elaborate the plan of attack for this problem as well?

**Comment by DennisSchwartz** [comment]
@alkesh47 Sorry, I meant to look at this on the weekend. 

I think it depends. Do you have a preference on the technology you'd like to use?
The current, temporary, landing page is this one: https://github.com/biojs/biojs.github.io

For us it would be easiest if we can host it on Github, but that would require the page to be built using Jekyll.
There are ways to use other technologies and then make it into a static site and deploy it to Github. But from the experience we've had in the past, I'd prefer not to mix technologies too much.

So if you'd like to use something else and maybe more JavaScript based (React, Angular), that's totally fine too, we would just need to find a different way to host.

**Comment by alkesh47** [comment]
@DennisSchwartz Well I was thinking maybe we could use Angular and find out a different way to host?

**Comment by rowlandm** [comment]
Happy to run with that - we can host on NecTAR VMs eventually ...

**Comment by alkesh47** [comment]
@DennisSchwartz  @rowlandm I have prepared a basic layout for the frontend portion of the website. I would be glad if you reviewed it and provide advise and feedback on the same https://github.com/alkesh47/Flowerhorn
I plan on using Angular as the javascript framework. Is there anything that I need to know which may prove useful in the future development process?

**Comment by rowlandm** [comment]
Would you consider vuejs? I know of two or three groups migrating to it,
including ours.  We favor it as it's lightweight but still separates html
from js. Angular is considered a heavy solution.

It's tricky as we need to balance what our contributors want to do/ have
the skillset to do versus maintainability and readability of the code.

I am not sure what is the best way forward. I think since Dennis does so
much technical work he should have final say.....

What is everyone else's thoughts?

**Comment by rowlandm** [comment]
Also, I would rule out react due to their implicit message behind their
licensing.

**Comment by alkesh47** [comment]
@rowlandm @DennisSchwartz Well honestly I too was thinking that Angular might be an overkill for this solution, so VueJS would be the most preferred option. Also I have more experience with VueJS so it would be comparitively easier to implement in Vue rather in Angular.

**Comment by ljgarcia** [comment]
React is currently under MIT, is not it?

vue.js seems a good option too, and yes, Angular is probably too heavy 
in this case

**Comment by rowlandm** [comment]
just a side note around React...

https://www.theregister.co.uk/2017/08/21/facebook_apache_openbsd_plus_license_dispute/

Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.

**Comment by yochannah** [comment]
They changed it following the uproar - like @ljgarcia says it's now MIT:

https://www.theregister.co.uk/2017/09/26/facebook_license_surgery_on_react/

**Comment by alkesh47** [comment]
@DennisSchwartz @rowlandm So what's the final say? Which one should we roll with?

**Comment by DennisSchwartz** [comment]
I don't mind. I like both vue.js and react from what I have heard from our front-end people here.
My personal preference would be React, just because I meant to get into it for a while ;)

So I think it's your choice between those two, unless @rowlandm has something to say on this :)

**Comment by DennisSchwartz** [comment]
Also, I looked at your design/layout(https://github.com/alkesh47/Flowerhorn) and it's looking really cool!

**Comment by rowlandm** [comment]
If it was my call, I would lean towards Vue. Alkesh has the experience,
it's lightweight and I don't think ReactJS is open source
<https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2>

Dennis, you would probably be helping to maintain it - so I think it's your
call.

Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.

**Comment by 4ndr01d3** [comment]
Hey Rowlan,
I guess you didn't see the update on the top of the article you are
sharing... Nonetheless if Alkesh is experienced in Vue and he is interested
in working on it, I don't see why no.

**Comment by DennisSchwartz** [comment]
If everyone is ok with Vue, then let's go with that :)

**Comment by alkesh47** [comment]
Then Vue it is :)
@DennisSchwartz  @rowlandm So how shall we approach this issue? I guess the best way to tackle this would be to follow the MVP approach.

**Comment by rowlandm** [comment]
Minimum Viable Product? Always :D

As Dennis said before, see if you can re-use the data that the current
module list uses just to be able to kick things off.

Then you should be able to see what is really needed.

Then you would have to do some profiling to see where the speed slowdowns
occur.

That's my suggestion.

Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.


On Thu, Feb 1, 2018 at 10:33 PM, Alkesh Srivastava <notifications@github.com

**Comment by alkesh47** [comment]
@rowlandm Sure thing, I'll see what I can salvage and start some profiling.

**Comment by DennisSchwartz** [comment]
Aw crap, I meant to send this on Friday but got distracted and forgot about it:

I can tell you that currently the API call to get the list of components is quite slow (seconds). The backend generates one big json object and sends it as a HTTP response. And it's currently not using a database, so it's doing a new search every time.

The new backend I'm working on now, will respond as a stream response using [hapi.js](https://hapijs.com/) from a MongoDB instance.
Not sure yet how that can be processed by the frontend though :) But it should mean the first components will be returned right away.

**Comment by rowlandm** [comment]
Are you sure you're OK doing this Dennis?

I'm happy with the speeds until we can get someone on it via GSOC?

Regards,

*Rowland Mosbergen | Stemformatics Project Manager*

Centre for Stem Cell Systems

Department of Anatomy and Neuroscience | Faculty of Medicine, Dentistry and
Health Sciences

Room 1.36, Level 1, Kenneth Myer Building

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 834 46623 *E: **rowland@stemformatics.org
<rowland@stemformatics.org>*

*I acknowledge the Wurundjeri people of the Kulin Nation as the Traditional
Owners of the land on which I work, and pay my respects to the Elders, past
and present.*



*[image: cid:image002.jpg@01D31D8F.E823DE70]*

 *CRICOS: 00116K*

This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The University
does not warrant that this email or any attachments are free from viruses
or defects. Please check any attachments for viruses and defects before
opening them. If this email is received in error, please delete it and
notify us by return email.

**Comment by DennisSchwartz** [comment]
That part is already done ;) But don't worry, there is plenty of work to do. But I think it would be good for a backend GSoC project to build on what's there already :)

**Comment by alkesh47** [comment]
@DennisSchwartz If you're returning stream responses from the backend, we can implement them on the front end either by using infinite scroll using vue watchers or by using something like [Clusterize.js](https://clusterize.js.org/) In our case, I guess the former would be a better choice. But again the choice boils down to our preference of how we want the data to be displayed on the front end.

**Comment by alkesh47** [comment]
@DennisSchwartz @rowlandm Congrats on getting selected for GSOC 2018 ! 😄 
Shall I begin working out a detailed plan and start preparing a rough prototype based on our current findings, or would you rather want me to get more familiar with the codebase and fix some issues?

**Comment by rowlandm** [comment]
I think a high level plan that also includes what we decide for our architecture. I think we need to focus on reliability and maintainability as we write up that plan. If the biojs goes down it needs to be easy to troubleshoot for people who didn't write it.

**Comment by rowlandm** [comment]
Oh and thanks!

**Comment by alkesh47** [comment]
Ok, I'm on it

**Comment by r0hit-gupta** [comment]
Hello everyone, I just tried designing a mock for the registry UI. Please let me know your thoughts and suggestions. I would love turning this prototype into a working product.

<img width="1280" alt="homescreen" src="https://user-images.githubusercontent.com/16841686/36914118-2f45d16c-1e72-11e8-9f1d-b990a7a06b3d.png">

**Comment by rowlandm** [comment]
that looks quite clean
what would the front page look like?

**Comment by abhinavvisen** [comment]
Hello, fellow DevNinjas.I am happy to be the part of this organization and contribute towards the project.Now coming to the current discussion according to my point of view "vuejs" is lighter compared to angular and React.We can say that Vuejs is sort of big brother of angular with more power and easy handling.Rest , whatever the whole developers and the mentors are comfortable with we could go with that framework @rowlandm @DennisSchwartz @yochannah .
@r0hit-gupta The design looks really neat.

**Comment by rowlandm** [comment]
What's a DevNinja? :)

I think we would probably stick with Vue - it's getting a fair bit of support here and in the networks that I know of.

**Comment by abhinavvisen** [comment]
Its actually sort of Ninja Developers :)

@rowlandm No problem I am ready to go with Vue.

**Comment by r0hit-gupta** [comment]
@abhinavvisen thank you 😃. Please let us know if it can be improved in some manner.

**Comment by abhinavvisen** [comment]
@r0hit-gupta Sure.Actually I have some things in my mind.I will let  know as soon as possible.
