### ISSUE TITLE
2018-06-28 BioJS Community call

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#44]
Description:BioJS Monthly Community Call (10.30am GMT  on the fourth Thursday of every month)

Please add in agenda in the comments below

https://unimelb.zoom.us/j/6552003787

https://groups.google.com/forum/#!forum/biojavascript

Or join Zoom by phone: 
    Dial: +61 2 8015 2088
    Meeting ID: 655 200 3787 
    International numbers available: https://unimelb.zoom.us/zoomconference?m=MB2Ciocm74cBW8nyXg3XVbGY5vqzsDnd

Or join Zoom from a H.323/SIP room system: 

    Dial: SIP:7588@aarnet.edu.au
    or H323:6552003787@182.255.112.21 (From Cisco)
    or H323:182.255.112.21##6552003787 (From LifeSize or Polycom) 
    or 162.255.36.11 or 162.255.37.11 (U.S.)
    Meeting ID: 6552003787

**Comment by yochannah** [comment]
I'm going to have to pass my apologies for this one - I'm at GCCBOSC

**Comment by rowlandm** [comment]
Engage with the Galaxy community before the hackathon - what kind of things would be useful for the end users?

**Comment by rowlandm** [comment]
Also - how do we target BioJS component developers?

**Comment by rowlandm** [comment]
Testimonials for helping BioJS - help sell the idea of helping

**Comment by rowlandm** [comment]
Talking about Galaxy in the next month

**Comment by ljgarcia** [comment]
Sorry I missed the call this morning. I have seen the comments, thanks 
Rowland for them. Galaxy is important, yes, good to talk about it next 
time.
