### ISSUE TITLE
July community call

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#46]
**EDIT: This will be at 11:30 UK time, NOT 10:30 - arewemeetingyet link below updated to reflect this**

If I'm right it should be this Thursday at ~10:30~ 11:30 AM UK time or check here for your timezone http://arewemeetingyet.com/London/2018-07-26/11:30  - does that sound correct? 

Agenda items:

- Biohackathon - we are accepted and should discuss
    - attendees? (Dennis + Yo + Leyla will definitely attend, should we seek funding for Megh and Sarthak?)
- GSoC - not long left! status update and wrapup plans?
- Galaxy Integration. @bgruening would you or another delegate be able to make it? If so, we could make sure to discuss it first so you can leave for the other boring stuff if needed. 
- Other?

**Comment by yochannah** [comment]
I think that the calendar reminders may have disappeared because they were tied to @rowlandm's stemformatics account. We should create a new set tied to one of the biojs google accounts, perhaps?

**Comment by sarthak-sehgal** [comment]
@rowlandm @DennisSchwartz and I discussed last month that we need to discuss about Galaxy integration and future plans for growth of BioJS.

**Comment by yochannah** [comment]
added - thanks @sarthak-sehgal !

**Comment by bgruening** [comment]
Yes, I will try to make it :) This will hack will be awesome!
ping @dannon

**Comment by dannon** [comment]
I'll try to make it, too.

**Comment by sarthak-sehgal** [comment]
@yochannah the website for biohackathon mentions that a few candidates will get funded but I don't see any procedure for the same. 
_"There will be a minimum of fifteen travel rewards for the invited applicants. The travel rewards will be offered on a case-by-case basis based on the application’s relevance to ELIXIR’s technical activities and strategy."_
Can you help me out here?

**Comment by rowlandm** [comment]
@yochannah it should be 10:30am GMT so 11.30 UK time.

**Comment by rowlandm** [comment]
https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=7&day=26&hour=10&min=30&sec=0&p1=152&p2=136&iv=1800

Can someone send me Leyla Garcia's email?

**Comment by yochannah** [comment]
@rowlandm the calendar invite doesn't match 11:30AM uk time, it comes through as 09:30 for me - can you tweak it to two hours later? I've sent you Leyla's address.

@sarthak-sehgal we have been _some_ funding for the hackathon allocated by elixir but it's probably not enough to get a large number of people there. There are some nice travel grant funds here that might be worth considering: https://www.wemakescholars.com/blog/international-conference-travel-grants - we'll discuss more details on the call.

**Comment by yochannah** [comment]
@dannon @bgruening pinging you directly to make sure you're aware it's an hour later than I originally suggested :)

**Comment by DennisSchwartz** [comment]
@sarthak-sehgal Let's talk about the process for applying for the travel rewards on the call. I'm also interested to understand how that usually works.

**Comment by dannon** [comment]
@yochannah Got it, even better for me, 6:30 AM instead of 5:30!

**Comment by yochannah** [comment]
I was wondering how early you'd have to get up for this :sweat_smile: - glad an hour later helps!

**Comment by rowlandm** [comment]
https://unimelb.zoom.us/j/6552003787  for @bgruening  and @dannon

**Comment by yochannah** [comment]
Notes: 

## Present: 

@sarthak-sehgal 
@rowlandm 
@yochannah
@bgruening 
@Megh-Thakkar 

Mostly discussed the hackathon, with notes here including some follow ups: 
- https://github.com/biojs/organisation/issues/47

Other than this: 
- GSoC on target, although we had to prioritise some tasks when we found that building unbundled biojs components timed out sometimes. 
- @bgruening will look up getting biojs some server space in EU: #48 

Tell @DennisSchwartz and @dannon about these notes!
