### ISSUE TITLE
August 2018 Community Call

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#49]
Hello one and all! My calendar says it's community call time this week - Thursday 23 August at 11:30 AM UK time, or you can check here for your timezone: http://arewemeetingyet.com/London/2018-08-23/11:30 

## Agenda (feel free to suggest additional topics)

1. GSoC: Wrapped up? Do we have any follow-up steps?
2. BioHackathon - possibly registration is closed :| - and we have some [actions that required follow-up](https://github.com/biojs/organisation/issues/47) - (followup items were assigned to @rowlandm @yochannah @bgruening)
   - community needs survey to help prioritise component integration: https://docs.google.com/forms/d/e/1FAIpQLSdvlAXB2x7ch996A_cTZioz081onQNsENZq2rpJ5G2urPuMiw/viewform - do we need to edit/add etc.
3. [German server resources for BioJS](https://github.com/biojs/organisation/issues/48) - (@bgruening)
4. Team kit & GSoC thank yous!! (Yo)

**Mentioning likely/possible attendees as a heads-up**

@sarthak-sehgal
@rowlandm
@bgruening
@Megh-Thakkar
@ljgarcia 
@DennisSchwartz 

## Joining instructions:

The meeting will take place in Rowland's Zoom room: https://unimelb.zoom.us/j/6552003787

**Comment by rowlandm** [comment]
I'll have to miss this call. Sorry.

**Comment by yochannah** [comment]
@rowlandm thanks for letting us know! Are we still ok to use your zoom room?

**Comment by rowlandm** [comment]
Of course!

**Comment by Megh-Thakkar** [comment]
@all can we start the call 30 minutes before time? I have a class at the exact time the call will start and I would like to join the conversation if possible.

**Comment by bgruening** [comment]
Small updates from my side, as I'm also not sure I can attend. We just need to wait for the CloudNetwork as soon as this is in place we can get some compute/hosting space for BioJS. So I assume in the next 2-3 weeks.

**Comment by yochannah** [comment]
@Megh-Thakkar that time works for me! Hopefully some of the others will chime in - @sarthak-sehgal @DennisSchwartz @ljgarcia ?

@bgruening thanks for the update! :)

**Comment by sarthak-sehgal** [comment]
I too have a class at 11:30 UK time so I'll be able to attend the call for about 20-25 minutes if it's at 11:00 UK time :)

**Comment by ljgarcia** [comment]
I could do it at 11, yes

**Comment by ljgarcia** [comment]
sorry, I am confused, do you want to start at 10am or 11am? both work 
for me, just please let me know

**Comment by yochannah** [comment]
@ljgarcia  11am :)

**Comment by yochannah** [comment]
The meeting ended up being pretty quick due to internet connectivity issues, but here are some quick notes

1. GSoC is over - planning to launch the new site soon, just needs a DNS switchover. WELL DONE ALL! :tada: :heart: 
2. Swag - 
   1. We'll be sending out some thank-yous to the GSoC mentors and students. You'll receive an email with a survey link for this. Biohackathon representatives can also have t-shirts if desired. 
   2. Stickers: Once we have a nice design we'll print out some hex stickers: https://github.com/biojs/organisation/issues/50 <-- WE NEED HELP FOR THIS! 
3. Biohackathon places are sold out - if Sarthak / Megh are successful in getting a travel fellowship we'll have to ask for places on the waiting list or if there's room to squeeze two more people in. 
4. Community needs survey - we've tweeted the link. Please share widely: https://twitter.com/BiojsLibrary/status/1032590648778661890
