### ISSUE TITLE
Migration of infrastructure

### ISSUE THREAD

**Issue by rowlandm** [biojs/organisation#5]
Hi All,

I got this email from Bjorn about payment for Amazon Web Services and Heroku running out as of now.

I can get Stemformatics to pay this til the end of the year. But we need to have a plan and ensure we move off these servers by 1st January 2018.

My plan is to host these on the Australian research cloud (NeCTAR) and to use this as a way to promote BioJS in Australia. That's the easy bit.

The key bit is to either move the infrastructure over to the NeCTAR cloud or to build everything from scratch.

I'm leaning towards building everything from scratch and copy/pasting anything of use that we can salvage.

Thoughts?

=========================================================

Dear Both

I hope this email finds you well.

As you know I have taken over from <redacted>.

I received an email today regarding payment of the following 
-Amazon Web Services (approx. £11.00 per month)
-Heroku (approx. £5.46 per month) for BioJS.

I understand from chatting to <redacted> that these used to be paid from Institute fundsbut unfortunately this funding source no longer exists as such it is not possible to provide this support in the future.

I therefore wanted to update you both so that you could make alternative arrangements.

**Comment by bgruening** [comment]
I'm missing technical background for what this all is needed, but my feeling is we should move over the website to one of our clouds.

**Comment by rowlandm** [comment]
I agree. It might be better to have the cloud based in Europe as opposed to Australia (NeCTAR). How quickly could we move it over?

Or would we need to build it from scratch?

**Comment by yochannah** [comment]
Another hosting option could be http://osuosl.org/services/hosting/ (USA-based)

**Comment by rowlandm** [comment]
Question is can we just migrate the code we currently have or do we need to build it from scratch?

**Comment by rowlandm** [comment]
Hackathon idea:
- Turn mockup into HTML
- try a simple 1 example BioJS viz from npm
- try a multi example BioJS viz from npm
- try to provide a list of BioJS npms into a website

**Comment by rowlandm** [comment]
I think we need to use VMs for the moment. This is the most simple way of keeping things going for the complexity we need.

**Comment by rowlandm** [comment]
Mozfest might be an option to recruit people.

**Comment by rowlandm** [comment]
Linux conference in January?

**Comment by DennisSchwartz** [comment]
I like the Idea of a Hackathon. I would of course prefer Europe or specifically Germany or UK :D

**Comment by rowlandm** [comment]
Lets look around for one there. I'm chasing one option over here.

El 27 oct. 2017 05:31, "Dennis Schwartz" <notifications@github.com>
escribió:

I like the Idea of a Hackathon. I would of course prefer Europe or
specifically Germany or UK :D

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/biojs/organisation/issues/5#issuecomment-339757746>,
or mute
the thread

**Comment by rowlandm** [comment]
We could look at using github as I can see raw files:

https://raw.githubusercontent.com/rowlandm/biojs-vis-rohart-msc-test/master/data/dataset6037.rohart.MSC.tsv

https://raw.githubusercontent.com/rowlandm/biojs-vis-rohart-msc-test/master/css/biojs-vis-rohart-msc-test.css

The hardest part is adding extra stuff for the simple example:
http://workmen.biojs.net/demo/biojs-vis-rohart-msc-test/simple

`<meta charset="UTF-8">
<link type="text/css" rel="stylesheet" href="/github/rowlandm/biojs-vis-rohart-msc-test/master/css/biojs-vis-rohart-msc-test.css">


<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.6.3/d3-tip.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="https://wzrd.in/bundle/biojs-vis-rohart-msc-test@0.4.0"></script>



<div id='snippetDiv'></div>

<script>
var rootDiv = document.getElementById('snippetDiv');`

**Comment by rowlandm** [comment]
Sorry everyone. But how can I pay for these services to keep going?

**Comment by rowlandm** [comment]
I tried to login to Heroku, but couldn't. Using credentials from the Infrastructure document.

**Comment by rowlandm** [comment]
Hi @DennisSchwartz could we get an update around status of migrating to NeCTAR VMs?

**Comment by DennisSchwartz** [comment]
@rowlandm I've now moved the workman to biojs1. However, the DNS hasn't updated yet, I'm hoping it'll work soon, otherwise I'll fall back and investigate.

So I can shutdown my own AWS account soon.

**Comment by rowlandm** [comment]
Great! Thanks Dennis!

**Comment by DennisSchwartz** [comment]
There was a small configuration error 🙊 But it's back up working now with the NeCTAR machine 👍 
For some reason I can't get it to accept https connections but it seems to be fine for biojs.io for now.

**Comment by DennisSchwartz** [comment]
I would say this is done for now. For new work to be done, we should create a new issue.
Please re-open if you disagree @yochannah @rowlandm
