### ISSUE TITLE
BioJS Hex stickers! 

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#50]
We're going to get some stickers printed to thank contributors and share with others. Is anyone's artistic skill up to putting this together? They probably need to just be the biojs logo + the word biojs. 

If you need hex sizing specs check out this thread: https://twitter.com/yoyehudi/status/930088898226769920 

**Output:** 
- sticker template in a raster format, ideally png
- sticker template in editable format such as svg 

Contributors will receive copies of the final stickers, of course!

**Comment by DennisSchwartz** [comment]
Also check this Folder for the last Sticker designs we had:
https://drive.google.com/drive/u/0/folders/0B7X2x2IPBve7MW4xWFJiTk5VTzQ

**Comment by yochannah** [comment]
![image](https://user-images.githubusercontent.com/9271438/48414208-fb4fc680-e741-11e8-9997-0782ae4eaece.png)

Anyone want some? Message me - my email's in my github profile or [@yoyehudi](https://twitter.com/yoyehudi) on twitter
