### ISSUE TITLE
September 2018 Community Call

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#52]
Hi folks! 
Just a quick agenda for our call today! http://arewemeetingyet.com/London/2018-09-27/11:30

## Agenda (contributions welcome as always
1. workmen seems to go down a lot for short periods of time
2. The new website does not have SSL certificates (HTTPS is not working)
3. Still need sticker designs & t-shirt designs - ordering soon! 
4. KnetMaps and genomaps were not listed in the registry?
5. Biohackathon

**Mentioning likely/possible attendees as a heads-up**

@sarthak-sehgal
@rowlandm
@bgruening
@Megh-Thakkar
@ljgarcia 
@DennisSchwartz 

## Joining instructions:

The meeting will take place in Rowland's Zoom room: https://unimelb.zoom.us/j/6552003787

**Comment by ljgarcia** [comment]
Hi Dennis,

I had the meeting scheduled at 10:30 UK but then I realized it will be 
11:30 UK. It clashes with another meeting so cannot join, sorry about 
it. Do you plan to discuss anything regarding the Paris BioHackathon 
next meeting? Did not see anything in the agenda this time. Who is 
joining the BioHack meeting on the 4th? It is for project leaders.

Have a great meeting! Will have a look to the minutes.

Cheers,

**Comment by yochannah** [comment]
Sarthak and possibly Megh can't make it either - I suggest we reschedule.

**Comment by DennisSchwartz** [comment]
I'm ok with that. Any suggestions?

**Comment by yochannah** [comment]
I can make most times up to and including 4pm UK time today or tomorrow. @ljgarcia @Megh-Thakkar @sarthak-sehgal Can you suggest some slots that would work for you all? 

I haven't heard from @rowlandm at all, so not sure if he's planning to attend.

**Comment by DennisSchwartz** [comment]
I'm pretty much free for the rest of the week. Not so much next week though :) 
I'll try to make a doodle in a bit.

**Comment by sarthak-sehgal** [comment]
Can we have it tomorrow at 11:30 UK time?

**Comment by DennisSchwartz** [comment]
Works for me! @yochannah @rowlandm @ljgarcia ?

**Comment by rowlandm** [comment]
happy to try it. might not make it though

**Comment by ljgarcia** [comment]
Hi,

Yes, tomorrow 11:30 it works.

Cheers,

**Comment by Megh-Thakkar** [comment]
I'll join it too!

**Comment by yochannah** [comment]
# Notes

1. Workmen: Uptime robot has been pinging us a lot, but it seems to be okay again now. Will ignore for now, unless anything else comes up. The workmen server is used for visualisations in the new site. 
2. For SSL, we'll use the mybiojs@gmail.com to set up let's encrypt. [ @Megh-Thakkar , @sarthak-sehgal ]
3. Stickers: @sarthak-sehgal will upload when he has his laptop back. These will also become the t-shirt designs. 
4. Adding BioJS components: some components didn't get added automatically. @Megh-Thakkar ran a database update to get them up - it should happen automatically every hour from here on (the cron jobs were stopped while we were migrating dns settings). 
5. Biohackathon - need to review [our application notes](https://docs.google.com/document/d/1kStrVSEQA3NC_rRz9vUCSNr-wXdCFGa9s5-RuHU--Ew/edit) and make further plans for hackathon

Community and sustainability 

let's consider writing a paper about the sustainability of open source communities. $0 budget sustainable communities - how does this sway our choices for technical implementations?

- Possibly two papers - one community oriented, one technical re: re-launch of site. 
- possible target: F1000 ELIXIR channel? 
- TODOS: 
   - literature review - what else is there out there?
   - create google doc and scaffold the paper. @DennisSchwartz 
   - scaffold due end of october - everyone welcome - @rowlandm please speak to @Megh-Thakkar @sarthak-sehgal 
   - @yochannah - consider also blogging about this on the SSI website?

**Comment by DennisSchwartz** [comment]
1. Workmen is currently only used for visualisations. A little bit of downtime is not an issue for now.

2. @Megh-Thakkar will set up SSL certificates for the new site. Using mybiojs@gmail.com to send notifications. @DennisSchwartz to review who has access to this email adress

3. @sarthak-sehgal will send sticker designs when his laptop is working again. (Some time next week?)

4. The cronjobs were stopped when moving domains. We then forgot to restart them after the move. @Megh-Thakkar has restarted them and it's all back to normal.
