### ISSUE TITLE
January 2019 Community Call

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#54]
Opening this discussion more publicly - we haven't had a community call in a while. I think our usual time of 10:30 or 11:30 UK time is a bit tricky for many of us - how about 13:00 UK time on Monday? http://arewemeetingyet.com/London/2019-01-07/13:00/BioJS

**Comment by yochannah** [comment]
Agenda: 

- Biohackathon reports (Dennis, Yo) 
- Updating BioJS standards (3.0 & webcomponents?)
- Updating BioJS site
- GSoC

Proposal: BioJS hack (upgrade your component day!) and/or Mozilla Global Sprint this year? 

Feel free to add items

**Comment by ljgarcia** [comment]
Hi Yo,

Would it be still on the last but one week of the month?

Regards,

**Comment by DennisSchwartz** [comment]
I can't on this Monday at 1pm. How about 2pm?

**Comment by yochannah** [comment]
@DennisSchwartz  2pm would work fine for me! Other timezones: http://arewemeetingyet.com/London/2019-01-07/14:00/BioJS

@ljgarcia I guess that's up for discussion. Do you have preferences?

**Comment by ljgarcia** [comment]
Hi Yo,

I do not mind the week but I already have a scheduled meeting for every 
first Monday of the month (Tuesday if bank holiday) so I could not join 
next Monday January the 7th.

I could not make it on first Monday of the month at 2pm, Wednesdays at 3 
pm, Fridays at 11am, third Friday of the month at 2pm. Those are 
recurrent meetings already scheduled for me.

Regards,

**Comment by yochannah** [comment]
Joining instructions - there is a link in the calendar invite, or visit here: https://hangouts.google.com/call/ZLjjld1Kx3z9eIXVBPrPAEEI

**Comment by yochannah** [comment]
So I deleted my original notes by accident (whoops). Here's my reconstruction from memory

**Continuous Deployment**
@DennisSchwartz has been totally awesome over christmas break and:
- added two CD pipelines: items merged into `master` are deployed to dev.niojs.net and commits merged to `production` are deployed to biojs.net. Nice!
- More owrk needed on the visualisations - we probably need to re-think snippets. 

**GSoC**
We'd like to participate again, but we feel like at this stage the BioJS 3.0 requirements aren't quite concrete enough to formulate a project idea. We'll revisit at the next meeting (two weeks - Jan 21). 

**BioJS 3.0**
We'd like to update our standards and EDU pages to make components higher standard. 

What we need at the minute: 
- Draft 3.0 proposal (Yo to complete by the 21st).
- Draft snippets style (Dennis & Sarthak to discuss - due by 21 January). 
- Update EDU with a clearer structure. 
    - How to contribute to BioJS Infrastructure 
    - How to _use_ BioJS components
    - How to _develop_ BioJS components. 

**Mozilla Global Sprint**
The next Global Sprint will be at the end of March (more: https://foundation.mozilla.org/en/opportunity/global-sprint/ ). This might be a nice opportunity to have an update-a-component-a-thon.

**Next Meeting**

We'll try an evening (UK) meeting if it's okay with others. @Megh-Thakkar - (and others) how do you feel about 17:00 UK time? I'm pretty sure that's 22:30 in India. http://arewemeetingyet.com/London/2019-01-21/17:00/BioJS%20Community%20call - this would work well as a regular time for @DennisSchwartz and @yochannah but we can look at other times if needed. 

If it sounds manageable we'll try to add a calendar appointment for it, and maybe use the InterMine video meeting room since Megh had difficulty joining this time.  

-----------------------

If I missed anything please add it!

**Comment by ljgarcia** [comment]
Hi all,

17:00 meeting for next time works for me, this time I had another 
meeting.

@Yo, happy to collaborate/provide feedback on the draft you are working 
on.

Kind regards,
