### ISSUE TITLE
January 2019 Community Call 2

### ISSUE THREAD

**Issue by yochannah** [biojs/organisation#56]
As noted in #54, we're moving calls to a different time slot, and will be meeting again in January to discuss our GSoC related plans. 

The next call will be on the 21st of January 2019, at 5PM UK time. 
In your timezone: http://arewemeetingyet.com/London/2019-01-21/17:00/BioJS%20Community%20call

## Agenda: 

1. Kudos to Dennis for so much work and two great blog posts! 
1. GSoC 2019 - do we feel ready to propose project ideas yet, and who will be mentoring? #41 
2. BioJS 3.0 draft: #55
3. Next call - do we all have access to the calendar?

## Joining instructions: 
Let's try to use the InterMine meeting room for this call:

Please join my meeting from your computer, tablet or smartphone.
https://global.gotomeeting.com/join/793189165

You can also dial in using your phone.
United Kingdom: +44 20 3713 5028

Access Code: 793-189-165

More phone numbers
United States: +1 (646) 749-3129
Germany: +49 692 5736 7317

First GoToMeeting? Let's do a quick system check:
https://link.gotomeeting.com/system-check

**Comment by yochannah** [comment]
Hey all - I have an unexpected conflict and need to take my kittycat to the vet tonight. :cat2: Can y'all go ahead without me?

**Comment by yochannah** [comment]
Okay - I'm tentatively able to re-schedule for the same time next monday, on the 28th. Does this sound do-able?

**Comment by DennisSchwartz** [comment]
yes from my side.

**Comment by yochannah** [comment]
Reminder all - the call is this evening in just over an hour!

**Comment by sarthak-sehgal** [comment]
Hello all,
I'm really sorry, I don't think I'll be able to attend the call. Got back
to college a day ago and caught severe cold and bad throat :(
I'll be able to communicate through gitter if that helps?

**Comment by yochannah** [comment]
@sarthak-sehgal oh no! Sorry to hear this :( Please take it easy and have some nice honeyed tea. :coffee: 

I think if others are available tonight we need to go ahead so we have plans before the gsoc application period closes. Feel free to add any thoughts or discussion points you may have - I'll try to take notes and maybe not accidentally delete them this time :laughing: 

Also, am I right in thinking you'd like to be a mentor this GSoC?

**Comment by sarthak-sehgal** [comment]
Yes, I'd love to mentor for BioJS this time. :)
I will share my ideas for the project latest by tomorrow.
I think we have to include that component test and error log thing we
discussed last week? I'll add it to my list and share tomorrow in case we
haven't included it yet.

**Comment by yochannah** [comment]
Okay -notes from last night: 

## GSoC Projects (See #41)
- It's important that we find a project that has a suitable 3-month scope and is reasonably well-defined. We feel like the scaffolder idea could comfortably fit this bill, the documentation idea would _not_ (but might be suitable for Google Summer of Docs, if that happens), and improving the visualisations on the registry _could_ be suitable but we'd need to flesh out the ideas better. Please add any further discussions on #41
- Mentors: Dennis, Yo, and Leyla will not be able to primary mentor this year, but Dennis & Yo can offer backup mentorship and advice, and Leyla is willing to help with applications. We would be happy to support @sarthak-sehgal as a primary mentor for a project. 

## Meetups
- Dennis is considering arranging BioJS meetups in Cambridge
- BOSC - we will try to attend CodeFest and do BioJS hacking there
- @ljgarcia tell us how to express interest in the Paris BioHackathon and a meeting arranged by the SSI in the Hague

## Servers
We're not sure when our server space runs out and we should expedite getting permanent resources!

**Comment by rowlandm** [comment]
Hi @yochannah 

Servers expire 27 Jul 2019 but I will be able to renew them for another year (it's a year to year thing).

**Comment by rowlandm** [comment]
What's concerning is that I don't think I can give anyone else access as it's all Australian Univeristy credential logins (nectar cloud)

**Comment by yochannah** [comment]
Thanks @rowlandm! I think that should keep us covered until we can find a permanent home - I will raise this again at the OBF board meeting to see if we can officially join.
