### ISSUE TITLE
[DevOps] biojs.net is down!

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#8]
As Rowland pointed out in the mailing list, the biojs.net page and the biojs.io registry are down.

Both were deployed to Heroku, where I can't access the account. I'm assuming it's been deactivated, possibly for missing the payments.

I will take a look into solutions as soon as I can. 
That will mostly involve:
- [x] Investigate reason for Heroku deactivation
- [x] Investigate possibly alternative solutions for hosting
- [x] Reactivate Heroku or deploy alternative.

Any help is appreciated.

@biojs/core

**Comment by DennisSchwartz** [comment]
While @xwatkins is working on a new implementation for biojs.net in https://github.com/biojs/biojs.github.io , I'm experimenting with deploying the existing Ghost CMS somewhere else. 

So far, little success. It's a bit of a mess that's misusing Ghost and node for things they shouldn't be doing.

**Comment by DennisSchwartz** [comment]
So I've got the workmen running in a docker container which is good enough to bring the registry at biojs.io back online.

Currently asking my boss if we can deploy it on [Repositive](www.repositive.io) infrastructure for now.
Otherwise I'll run it on a new AWS machine.

**Comment by DennisSchwartz** [comment]
The registry is back! http://biojs.io/

I'm not sure if the preview works, and we'll have to see if there are any other issues, but in general, it works.

I have created a container for the https://github.com/biojs/registry-workmen code and deployed it to the AWS container service. Tbh, I have no idea how it works. I doesn't have a database or Github token specified, but it seems to be jugging along just fine.

**Comment by yochannah** [comment]
WELL DONE!!

**Comment by wilzbach** [comment]
@DennisSchwartz @rowlandm @yochannah who is in charge of biojs.net nowadays?

Apparently the DNS entry for msa.biojs.net has been deleted. It should be a CNAME to `wilzbach.github.io`
Could someone look into this? Thanks a lot in advance!

See also: https://help.github.com/articles/setting-up-a-custom-subdomain/

CC @TatyanaGoldberg

**Comment by DennisSchwartz** [comment]
@wilzbach We've been discussing this on the mailing list. @rafael-alcantara is currently in charge of that and he changed the DNS entry of biojs.net to point to the new interim biojs site.

I've asked him to point it back to Cloudflare but haven't heard back so far.

**Comment by yochannah** [comment]
Hey @wilzbach! We're working on getting everything back up at the moment, but I think only Rafa has access to the domain. I need to apologise for this - I asked him to redirect it initially since our heroku hosting for the main site had gone down, and I didn't realise that the subdomains were all managed via cloudflare, and would break as a consequence :(

**Comment by rafael-alcantara** [comment]
Sorry to invade the conversation, but my name has been mentioned and I am afraid I am not the right Rafa :smile: Try Jiménez.

**Comment by DennisSchwartz** [comment]
🙈  @rafael-alcantara, my bad! @rajido is who I meant haha.

**Comment by rajido** [comment]
Now biojs.net pointing to the cloudflare nameservers
elinore.ns.cloudflare.com
jerry.ns.cloudflare.com

@DennisSchwartz are the cloudflare DNS configured to point to the biojs github pages?

**Comment by DennisSchwartz** [comment]
@rajido Thanks a lot! Biojs.io is working again :)

It's not pointing to the new Github pages yet, but I'll take care of that now.

**Comment by wilzbach** [comment]
Thanks a lot @DennisSchwartz @rajido :)

**Comment by DennisSchwartz** [comment]
Cloudflare should be reactivated and point to Github. It says it will take a few hours to be in effect, I will check back tonight.

**Comment by DennisSchwartz** [comment]
🎉  It's back! [https://www.biojs.net](https://www.biojs.net)

Thanks @rajido for fixing it and thanks to @xwatkins for putting together a replacement website on such short notice.

**Comment by rowlandm** [comment]
Thanks everyone!

**Comment by rowlandm** [comment]
I will close this issue now. Please re-open if you think you need to @DennisSchwartz
